# ============================================================
# MEMBER 5 - RISK ENGINE
# ============================================================
#
# Receives:
#   1. Clone probability      -> Member 3
#   2. Speaker match score    -> Member 4
#   3. Conversation risk      -> Member 4
#   4. Suspicious phrases     -> Member 4
#
# Produces:
#   - Risk Score
#   - Risk Level
#   - Decision
#   - Recommended Action
# ============================================================


def calculate_risk(
    clone_probability,
    speaker_match_score,
    conversation_risk_score,
    suspicious_phrases
):
    """
    Calculate the final fraud risk score.

    All scores are expected to be between 0 and 100.
    """

    # --------------------------------------------------------
    # 1. Convert speaker match into identity risk
    # --------------------------------------------------------
    # High speaker match = low risk
    # Low speaker match  = high risk

    speaker_risk = 100 - speaker_match_score

    # --------------------------------------------------------
    # 2. Suspicious phrase risk
    # --------------------------------------------------------
    # If suspicious phrases are detected,
    # assign maximum phrase risk.

    phrase_risk = 100 if suspicious_phrases else 0

    # --------------------------------------------------------
    # 3. Calculate weighted final risk score
    # --------------------------------------------------------

    risk_score = (
        (clone_probability * 0.40)
        + (speaker_risk * 0.25)
        + (conversation_risk_score * 0.25)
        + (phrase_risk * 0.10)
    )

    # Keep score between 0 and 100
    risk_score = round(
        min(max(risk_score, 0), 100),
        2
    )

    # --------------------------------------------------------
    # 4. Determine risk level and action
    # --------------------------------------------------------

    if risk_score <= 30:

        risk_level = "LOW"
        decision = "GENUINE"
        action = "ALLOW"

    elif risk_score <= 60:

        risk_level = "MEDIUM"
        decision = "SUSPICIOUS"
        action = "MONITOR"

    elif risk_score <= 80:

        risk_level = "HIGH"
        decision = "SUSPICIOUS"
        action = "FLAG_FOR_REVIEW"

    else:

        risk_level = "CRITICAL"
        decision = "FRAUDULENT"
        action = "BLOCK_AND_REVIEW"

    # --------------------------------------------------------
    # 5. Return final result
    # --------------------------------------------------------

    return {
        "riskScore": risk_score,
        "riskLevel": risk_level,
        "decision": decision,
        "recommendedAction": action
    }


# ============================================================
# MEMBER 4 → MEMBER 5 CONNECTOR
# ============================================================

def calculate_risk_from_analysis(
    clone_probability,
    analysis_result
):
    """
    Receives the combined result generated by
    Member 4's pipeline.py.

    Member 4 output format:

    {
        "claimed_identity": ...,
        "speaker_match_score": ...,
        "identity_verified": ...,
        "transcript": ...,
        "conversation_risk_score": ...,
        "risk_flags": ...,
        "matched_phrases": ...
    }
    """

    return calculate_risk(

        # Member 3
        clone_probability=clone_probability,

        # Member 4 - Speaker Verification
        speaker_match_score=analysis_result[
            "speaker_match_score"
        ],

        # Member 4 - Conversation Analysis
        conversation_risk_score=analysis_result[
            "conversation_risk_score"
        ],

        # Member 4 - Suspicious phrases
        suspicious_phrases=analysis_result[
            "matched_phrases"
        ]
    )


# ============================================================
# TEST
# ============================================================

if __name__ == "__main__":

    # --------------------------------------------------------
    # Simulated Member 3 result
    # --------------------------------------------------------

    clone_probability = 92

    # --------------------------------------------------------
    # Simulated Member 4 result
    # This has the SAME structure returned by pipeline.py
    # --------------------------------------------------------

    member4_result = {

        "claimed_identity": "user123",

        "speaker_match_score": 40,

        "identity_verified": False,

        "transcript": "Please send the OTP",

        "conversation_risk_score": 80,

        "risk_flags": [
            "OTP_REQUEST"
        ],

        "matched_phrases": [
            "send OTP",
            "transfer money"
        ]
    }

    # --------------------------------------------------------
    # Send Member 4 result to Risk Engine
    # --------------------------------------------------------

    final_result = calculate_risk_from_analysis(
        clone_probability,
        member4_result
    )
    # --------------------------------------------------------
    # Display result
    # --------------------------------------------------------

    print("\n===================================")
    print("       FINAL RISK RESULT")
    print("===================================")

    print("Risk Score         :", final_result["riskScore"])
    print("Risk Level         :", final_result["riskLevel"])
    print("Decision            :", final_result["decision"])
    print("Recommended Action :", final_result["recommendedAction"])

    print("===================================")